FORMAT: 1A

# Data Structures

## Instruction
+ id (number, required)
+ name: Инструкция по сбору X баннера (string, required)

## NewDetail (object)
+ count: 2 (number, required)
+ name: Пластиковая ножка с держателем ролла (string, required)
+ shortName: A (string, required)
+ link: http://teamcenter.indieteam.ru/1.zip (string, required)

## Detail (object)
+ id (number, required)
+ count: 2 (number, required)
+ name: Пластиковая ножка с держателем ролла (string, required)
+ shortName: A (string, required)

## NewStep (object)
+ description: Взять деталь A (string, required)

## Step (object)
+ id (number, required)
+ description: Взять деталь A (string, required)

## ControlPoints
+ id (number, required)
+ username: ivanov (string, required)
+ time: 1234567890 (number, required)
+ instructionId: 1 (number, required)

# ARIS

## Инструкции [/api/v1/instructions]

### Создать инструкцию [POST /api/v1/instructions]

+ Request 200 (application/json)
    + Attributes
        + name: Инструкция по сбору X баннера (string, required)
        + details (array[NewDetail], required, fixed-type)
        + steps (array[NewStep], required, fixed-type)

+ Response 200 (application/json)

### Получить инструкции [GET /api/v1/instructions]

+ Response 200 (application/json)
    + Attributes
        + instructions (array[Instruction], required, fixed-type)

### Получить инструкцию [GET /api/v1/instructions/{id}]

+ Parameters
    + id: 1 (string, required)

+ Response 200 (application/json)
    + Attributes
        + details (array[Detail], required, fixed-type)
        + steps (array[Step], required, fixed-type)

## Контрольные точки [/control_points]

### Получить контрольные точки [GET /api/v1/control_points]

+ Response 200 (application/json)
    + Attributes
        + control_points (array[ControlPoints], required, fixed-type)

### Создать контрольную точку [POST /api/v1/control_points/{username}]

+ Parameters
    + username: ivanov (string, required)

+ Response 200 (application/json)
